### ISSUE TITLE
[Feature Request] Shift Internal Scrollbar to Root of Page

### ISSUE THREAD

**Issue by shaneholloman** [CurtisDS/sd-model-preview-xd#7]
Hi there. Firstly, this extension is a personal favourite and is a fantastic way to track and keep assets organised with docs attached. Well done

I have forked this to allow me to restyle the cards to match the extra network styling and some extra tidbits. The item currently out of my skill scope is I'd like to remove the scroll bar. I find it a hindrance to viewing when there is a handful of images and docs

Cheers, again fantastic. I hope you keep this alive

**Comment by CurtisDS** [comment]
There shouldnt be a second scroll bar. So Im a bit confused. Can you post a screenshot and tell me what browser you are using?

**Comment by shaneholloman** [comment]
Ah, yes you are totally right, I should say the scrollbar has moved inside the page rather than at the root of the page

somehow the scrollbar is shifted inside the page:
![image](https://user-images.githubusercontent.com/1563909/218944542-81cd45ef-f6dc-47b9-a67f-24e4f1576593.png)

vs this which allows a page scroll to show more images:

![image](https://user-images.githubusercontent.com/1563909/218944797-bea8ebf8-c3db-4068-ad11-c4e680d3003a.png)

**Comment by shaneholloman** [comment]
If it's a plava to deal with, maybe you could let me know what block the scrollbar is in (file and line number) and I'll make it a learning experience : ). I'm a DevOps engineer with no python chops

**Comment by CurtisDS** [comment]
So i have good news and bad news.

Good news, I now understand what youre asking for
Bad news, Its a "plava" to deal with lmao
Good news, you can remove the inner scroll bar from most preview pages by deleting these lines from the style.css file:

Lines 2-4:
https://github.com/CurtisDS/sd-model-preview-xd/blob/d0e3d6bb549fff13fced3db45959b3d12a8f4a82/style.css#L2-L4

Lines 31-37:
https://github.com/CurtisDS/sd-model-preview-xd/blob/d0e3d6bb549fff13fced3db45959b3d12a8f4a82/style.css#L31-L37

However, I dont suggest you do that.

I would suggest you create a `user.css` file in the root of your a1111 folder and just add this css to negate what those lines are doing:

```CSS
.gradio-container > .flex > div.mx-auto.container {
	display: block;
}

#tab_modelpreview_xd_interface > div {
	position: relative;
	top: unset;
	bottom: unset;
	right: unset;
	left: unset;
}
```

Otherwise it'll cause issues if you do a git pull. But I also dont know what you got going on with your forked code so, ill leave that up to you.

Unfortunately (this might not apply to you) some more bad news is that doing this will pretty much break the ability to use HTML preview files. Because they are rendered in iframes the html doesn't know what height to set the div at, which is why I changed the UI to use flex layouts instead of block. This allowed me to set the area for the iframe to be everything south of the tab bar... but I didnt realize on wide screens like yours... or where you have multiple rows of tabs... that space gets pretty cramped.

So if you do make this change you may also want to add some CSS to set the height of the iframes to something reasonable like 800px. There will be a second scroll bar that is rendered inside the iframe but there is nothing you can do about it. Unless you set the height of the iframe to a value which is greater than what the contents need... but... there isn't really a good way to handle that and keep it responsive.

I did some thinking today but couldn't get to a solution that felt good. So ill do some more thinking and maybe figure something out. But for now, if you don't use HTML preview pages, I would add that CSS to your `user.css` file and that should solve your problem.

Example of hard coding the iframe height to a fixed value so that HTML preview files are still somewhat usable:
```CSS
#tab_modelpreview_xd_interface iframe {
	height: 800px;
}
```

**Comment by shaneholloman** [comment]
Excellent solution to show full cards - mardown docs render at the bottom of the page too. 

**So I'm stoked**

I added this to my user.css file

```css
.gradio-container > .flex > div.mx-auto.container {
	display: block;
}

#tab_modelpreview_xd_interface > div {
	position: relative;
	top: unset;
	bottom: unset;
	right: unset;
	left: unset;
}
```

Pages render thusly:

![image](https://user-images.githubusercontent.com/1563909/219279083-e1c8d172-5c34-40dd-a12c-6a7a0d6b4449.png)
